version: '3.1'

services:
  postgres:
    container_name: delivery_service
    image: postgres:14.8
    environment:
      POSTGRES_DB: sweet_bites_delivery_service
      POSTGRES_USER: pingwit
      POSTGRES_PASSWORD: pingwit_password
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5433:5432"

  delivery-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sweet_bites_delivery_service
      SPRING_DATASOURCE_USERNAME: pingwit
      SPRING_DATASOURCE_PASSWORD: pingwit_password
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres-db:
    driver: local
