version: '3.1'

services:
  postgres:
    container_name: delivery_service
    image: postgres:14.8
    environment:
      POSTGRES_DB: sweet_bites_delivery_service
      POSTGRES_USER: pingwit
      POSTGRES_PASSWORD: pingwit_password
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5433:5432"

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  delivery-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sweet_bites_delivery_service
      SPRING_DATASOURCE_USERNAME: pingwit
      SPRING_DATASOURCE_PASSWORD: pingwit_password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - kafka

volumes:
  postgres-db:
    driver: local
