version: '3.1'

services:
  postgres:
    container_name: delivery_service
    image: postgres:14.8
    environment:
      POSTGRES_DB: sweet_bites_delivery_service
      POSTGRES_USER: pingwit
      POSTGRES_PASSWORD: pingwit_password
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5433:5432"

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2182:2181"  # изменен порт на 2182
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - /tmp/zookeeper
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182  # изменен порт на 2182
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  delivery-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sweet_bites_delivery_service
      SPRING_DATASOURCE_USERNAME: pingwit
      SPRING_DATASOURCE_PASSWORD: pingwit_password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - kafka
    networks:
      - kafka-net

volumes:
  postgres-db:
    driver: local

networks:
  kafka-net:
    driver: bridge
